services:
  server:
    image: python:alpine3.19
    container_name: web-terminal-backend
    volumes:
      - ./server:/app
      - ./server/entrypoint.sh:/entrypoint.sh
#      - docker_sock:/var/run/docker.sock
#      - docker_bin:/usr/local/docker_bin
    ports:
      - 5000:5000
    privileged: true
    entrypoint: /entrypoint.sh
    depends_on:
      - docker

  client:
    image: node:lts-alpine3.19
    container_name: web-terminal-frontend
    volumes:
      - ./client:/app
    ports:
      - 3001:3000
    working_dir: "/app"
    command: "npm start"

  docker:
#    image: docker:20.10-dind
    build:
      dockerfile: docker/Dockerfile
      context: .
    container_name: web-terminal-docker
    privileged: true
    ports:
      - 2376:2376
      - 2375:2375
#    volumes:
#      - docker_sock:/var/run/docker.sock
#      - docker_bin:/usr/local/bin

volumes:
  docker_sock:
  docker_bin: