version: "3"

services:
  server:
    image: python:alpine3.19
    container_name: web-terminal-backend
    environment:
      DOCKER_TLS_VERIFY: 1
      DOCKER_CERT_PATH: /certs/client
    volumes:
      - ./server:/app
      - ./server/entrypoint.sh:/entrypoint.sh
      - ./docker/certs:/certs
    ports:
      - 5000:5000
    privileged: true
    entrypoint: /entrypoint.sh
    depends_on:
      - docker

  client:
    image: node:lts-alpine3.19
    container_name: web-terminal-frontend
    volumes:
      - ./client:/app
    ports:
      - 3001:3000
    working_dir: "/app"
    command: "npm start"

  docker:
#    image: docker:20.10-dind
    build:
      dockerfile: docker/Dockerfile
      context: .
    container_name: docker
    privileged: true
    ports:
      - 8000:2375
      - 9000:2376
      - 7000:7000
    volumes:
      - ./docker/certs:/certs
#      - /temp/docker.sock:/var/run/docker.sock
#    command: "socat TCP-LISTEN:7000,reuseaddr,fork unix:///var/run/docker.sock &"

#  socat_rdp_tcp:
#    image: alpine/socat
#    container_name: socat_rdp_tcp
#    command: "TCP-LISTEN:7000,reuseaddr,fork unix:///var/run/docker.sock"
#    volumes:
#      - /temp/docker.sock:/var/run/docker.sock:ro
#    ports:
#      - 7000:7000
