version: "3"

services:
  server:
    image: python:alpine3.19
    container_name: web-terminal-backend
    volumes:
      - ./server:/app
      - ~/.kube/config:/.kube/config
    ports:
      - 5001:5000
    privileged: true
    command: "/app/venv/bin/python /app/run.py"

  client:
    image: node:lts-alpine3.19
    container_name: web-terminal-frontend
    volumes:
      - ./client:/app
    ports:
      - 3001:3000
    working_dir: "/app"
    command: "npm start"
