apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: websocket-user-pod-attach-exec
  namespace: default
subjects:
- kind: ServiceAccount
  name: websocket-user
  namespace: default
roleRef:
  kind: Role
  name: pod-attach-exec
  apiGroup: rbac.authorization.k8s.io
