apiVersion: batch/v1
kind: CronJob
metadata:
  name: pod-cleanup
spec:
  schedule: "* * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: websocket-user
          containers:
          - name: kubectl-container
            image: bitnami/kubectl:latest # This image includes kubectl
            command:
            - /bin/bash
            - -c
            - |
              kubectl get pod -o json | jq -r --argjson timestamp 60 '.items[] | select (.metadata.creationTimestamp | fromdate < now - $timestamp).metadata.name' | xargs -r -L1 kubectl delete pod
          restartPolicy: OnFailure