apiVersion: v1
kind: Service
metadata:
  name: docker-service
spec:
  selector:
    app: docker-service
  type: LoadBalancer
  ports:
  - name: docker
    port: 8000
    targetPort: 2375
  - name: secure-docker
    port: 9000
    targetPort: 2376
  - name: custom-port
    appProtocol: ws
    port: 7000
    targetPort: 7000