apiVersion: apps/v1
kind: Deployment
metadata:
  name: docker-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: docker-service
  template:
    metadata:
      labels:
        app: docker-service
    spec:
      containers:
      - name: docker
        image: web-terminal-docker:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 2375
        - containerPort: 2376
        volumeMounts:
        - name: certs
          mountPath: /certs
        - name: docker-sock
          mountPath: /var/run
        securityContext:
          privileged: true
      - name: docker-socket-proxy
        image: alpine/socat
        command:
          - "socat"
          - "TCP-LISTEN:7000,reuseaddr,fork"
          - "UNIX-CONNECT:/var/run/docker.sock"
        ports:
          - containerPort: 7000
        volumeMounts:
          - name: docker-sock
            mountPath: /var/run
            readOnly: true
      volumes:
      - name: certs
        hostPath:
          path: /mnt/c/Data/Projects/web-terminal
      - name: docker-sock
        emptyDir: {}