# server-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-terminal-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-terminal-backend
  template:
    metadata:
      labels:
        app: web-terminal-backend
    spec:
      containers:
      - name: server
        image: web-terminal-backend:latest
        imagePullPolicy: Never
#        env:
#        - name: DOCKER_TLS_VERIFY
#          value: "1"
#        - name: DOCKER_CERT_PATH
#          value: "/certs/client"
#        tty: true
#        stdin: true
#        volumeMounts:
#        - name: kubectl-config
#          mountPath: /.kube/config
#          subPath: config
#        - name: entrypoint-script
#          mountPath: /entrypoint.sh
#          subPath: entrypoint.sh
#        - name: certs
#          mountPath: /certs
        ports:
        - containerPort: 5000
#        securityContext:
#          privileged: true
#        command: ["/entrypoint.sh"]
#      volumes:
#      - name: kubectl-config
#        hostPath:
#          path: /home/samarth/.kube/config
#          type: File
#      - name: entrypoint-script
#        hostPath:
#          path: ./../server/entrypoint.sh
#      - name: certs
#        hostPath:
#          path: ./../docker/certs

